name: Reusable Test
on:
  workflow_call:
    inputs:
      coverage:
        description: "Whether to upload coverage reports"
        required: false
        default: false
        type: boolean
    outputs:
      unit_test_result:
        description: "Result of the unit test job"
        value: ${{ jobs.unit-test.result }}

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run unit tests
        if: ${{ inputs.coverage == false }}
        run: bun run test

      - name: Run unit tests with coverage
        if: ${{ inputs.coverage == true }}
        run: bun run test:coverage

      - name: Upload unit test coverage
        if: ${{ inputs.coverage == true }}
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-coverage
          path: coverage/
          retention-days: 5
